# Cổng tiêu chuẩn
listening-port=3478
# Lắng nghe mọi IP nội bộ
listening-ip=172.26.6.137

# THAY BẰNG IP PUBLIC MỚI CỦA LIGHTSAIL
relay-ip=172.26.6.137
external-ip=13.251.143.234
realm=turn.oeb20412.com
user=rushcord:67696162616f

# Dải port Media (Đã mở trên Dashboard Lightsail)
min-port=50000
max-port=51000

fingerprint
lt-cred-mech
stale-nonce=600

log-file=/var/log/turnserver.log
simple-log