listening-port=3478
# Ép lắng nghe trên IP Public

tls-listening-port=443
cert=/etc/letsencrypt/live/turn.oeb20412.com/fullchain.pem
pkey=/etc/letsencrypt/live/turn.oeb20412.com/privkey.pem

listening-ip=161.248.147.166
relay-ip=161.248.147.166
external-ip=161.248.147.166

realm=turn.oeb20412.com
user=rushcord:67696162616f

# Dải port cho Relay (Vẫn cần mở TCP dải này trên Firewall)
min-port=50000
max-port=51000

fingerprint
lt-cred-mech
stale-nonce=600
log-file=/var/log/turnserver.log
simple-log